# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  push:
    paths:
      - "**.tex"
      - "**.ttf"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: LaTeX compilation
        uses: xu-cheng/latex-action@v3
        with:
          # The root LaTeX file to be compiled
          root_file: cv.tex
          # LaTeX engine to be used
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cv
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cv.pdf
